### ISSUE TITLE
iam not a programmer but i real need it ,so would you tell me how to use it 

### ISSUE THREAD

**Issue by yucheen** [integralfx/GPUFanControl#13]
i think it works now ,it's so nice
really hope it can start with windows can background process
thank you

**Comment by integralfx** [comment]
You can use Task Scheduler to start up with Windows.

Make sure "Run with highest privileges" is checked.

For some reason you have to re-do your settings but they will be saved.

**Comment by yucheen** [comment]
please add control ryzen 5950X
QAQ













At 2020-07-24 15:37:40, "integralfx" ***@***.***> wrote:

You can use Task Scheduler to start up with Windows.

Make sure "Run with highest privileges" is checked.

For some reason you have to re-do your settings but they will be saved.

**Comment by integralfx** [comment]
I'd recommend using [FanControl](https://github.com/Rem0o/FanControl.Releases) as my SysFanControl is no longer being actively worked on
